/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractKM3ScopeProvider extends DelegatingScopeProvider {
}
