/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class KM3RuntimeModule extends AbstractKM3RuntimeModule {
}
