<?xml version="1.0" encoding="ISO-8859-1"?>
<km3:Metamodel xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:km3="http://www.eclipse.org/gmt/2005/KM3">
  <contents name="Sample">
    <contents xsi:type="km3:Class" name="A" isAbstract="true">
      <structuralFeatures xsi:type="km3:Attribute" name="name" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.7"/>
    </contents>
    <contents xsi:type="km3:Class" name="B" isAbstract="true">
      <structuralFeatures xsi:type="km3:Attribute" name="kind" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.2"/>
    </contents>
    <contents xsi:type="km3:Enumeration" name="Kind">
      <literals name="secondKind"/>
      <literals name="firstKind"/>
    </contents>
    <contents xsi:type="km3:Class" name="C" isAbstract="false" supertypes="//@contents.0/@contents.0">
      <structuralFeatures xsi:type="km3:Attribute" name="value" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.6"/>
    </contents>
    <contents xsi:type="km3:Class" name="D" isAbstract="false" supertypes="//@contents.0/@contents.0 //@contents.0/@contents.1">
      <structuralFeatures xsi:type="km3:Attribute" name="isIt" lower="1" upper="1" isOrdered="false" isUnique="false" type="//@contents.0/@contents.5"/>
    </contents>
    <contents xsi:type="km3:DataType" name="Boolean"/>
    <contents xsi:type="km3:DataType" name="Integer"/>
    <contents xsi:type="km3:DataType" name="String"/>
  </contents>
</km3:Metamodel>
