/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext.scoping


/**
 * This class contains custom scoping description.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#scoping
 * on how and when to use it.
 */
class KM3ScopeProvider extends AbstractKM3ScopeProvider {

}
