/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext.ide.contentassist.antlr;

import com.google.inject.Inject;
import java.util.Collection;
import java.util.HashMap;
import java.util.Map;
import org.antlr.runtime.RecognitionException;
import org.eclipse.m2m.km3.xtext.ide.contentassist.antlr.internal.InternalKM3Parser;
import org.eclipse.m2m.km3.xtext.services.KM3GrammarAccess;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ide.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

public class KM3Parser extends AbstractContentAssistParser {

	@Inject
	private KM3GrammarAccess grammarAccess;

	private Map<AbstractElement, String> nameMappings;

	@Override
	protected InternalKM3Parser createParser() {
		InternalKM3Parser result = new InternalKM3Parser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getModelElementAccess().getAlternatives(), "rule__ModelElement__Alternatives");
					put(grammarAccess.getStructuralFeatureAccess().getAlternatives(), "rule__StructuralFeature__Alternatives");
					put(grammarAccess.getClassifierAccess().getAlternatives(), "rule__Classifier__Alternatives");
					put(grammarAccess.getMetamodelAccess().getGroup(), "rule__Metamodel__Group__0");
					put(grammarAccess.getMetamodelAccess().getGroup_4(), "rule__Metamodel__Group_4__0");
					put(grammarAccess.getMetamodelAccess().getGroup_4_3(), "rule__Metamodel__Group_4_3__0");
					put(grammarAccess.getPackageAccess().getGroup(), "rule__Package__Group__0");
					put(grammarAccess.getPackageAccess().getGroup_8(), "rule__Package__Group_8__0");
					put(grammarAccess.getPackageAccess().getGroup_8_3(), "rule__Package__Group_8_3__0");
					put(grammarAccess.getClassifier_ImplAccess().getGroup(), "rule__Classifier_Impl__Group__0");
					put(grammarAccess.getDataTypeAccess().getGroup(), "rule__DataType__Group__0");
					put(grammarAccess.getEnumerationAccess().getGroup(), "rule__Enumeration__Group__0");
					put(grammarAccess.getEnumerationAccess().getGroup_6(), "rule__Enumeration__Group_6__0");
					put(grammarAccess.getEnumerationAccess().getGroup_6_3(), "rule__Enumeration__Group_6_3__0");
					put(grammarAccess.getEnumLiteralAccess().getGroup(), "rule__EnumLiteral__Group__0");
					put(grammarAccess.getTemplateParameterAccess().getGroup(), "rule__TemplateParameter__Group__0");
					put(grammarAccess.getClassAccess().getGroup(), "rule__Class__Group__0");
					put(grammarAccess.getClassAccess().getGroup_8(), "rule__Class__Group_8__0");
					put(grammarAccess.getClassAccess().getGroup_8_3(), "rule__Class__Group_8_3__0");
					put(grammarAccess.getClassAccess().getGroup_9(), "rule__Class__Group_9__0");
					put(grammarAccess.getClassAccess().getGroup_9_3(), "rule__Class__Group_9_3__0");
					put(grammarAccess.getClassAccess().getGroup_10(), "rule__Class__Group_10__0");
					put(grammarAccess.getClassAccess().getGroup_10_3(), "rule__Class__Group_10_3__0");
					put(grammarAccess.getClassAccess().getGroup_11(), "rule__Class__Group_11__0");
					put(grammarAccess.getClassAccess().getGroup_11_3(), "rule__Class__Group_11_3__0");
					put(grammarAccess.getTypedElement_ImplAccess().getGroup(), "rule__TypedElement_Impl__Group__0");
					put(grammarAccess.getStructuralFeature_ImplAccess().getGroup(), "rule__StructuralFeature_Impl__Group__0");
					put(grammarAccess.getStructuralFeature_ImplAccess().getGroup_18(), "rule__StructuralFeature_Impl__Group_18__0");
					put(grammarAccess.getStructuralFeature_ImplAccess().getGroup_18_3(), "rule__StructuralFeature_Impl__Group_18_3__0");
					put(grammarAccess.getStructuralFeature_ImplAccess().getGroup_19(), "rule__StructuralFeature_Impl__Group_19__0");
					put(grammarAccess.getStructuralFeature_ImplAccess().getGroup_19_3(), "rule__StructuralFeature_Impl__Group_19_3__0");
					put(grammarAccess.getAttributeAccess().getGroup(), "rule__Attribute__Group__0");
					put(grammarAccess.getAttributeAccess().getGroup_18(), "rule__Attribute__Group_18__0");
					put(grammarAccess.getAttributeAccess().getGroup_18_3(), "rule__Attribute__Group_18_3__0");
					put(grammarAccess.getAttributeAccess().getGroup_19(), "rule__Attribute__Group_19__0");
					put(grammarAccess.getAttributeAccess().getGroup_19_3(), "rule__Attribute__Group_19_3__0");
					put(grammarAccess.getReferenceAccess().getGroup(), "rule__Reference__Group__0");
					put(grammarAccess.getReferenceAccess().getGroup_20(), "rule__Reference__Group_20__0");
					put(grammarAccess.getReferenceAccess().getGroup_20_3(), "rule__Reference__Group_20_3__0");
					put(grammarAccess.getReferenceAccess().getGroup_21(), "rule__Reference__Group_21__0");
					put(grammarAccess.getReferenceAccess().getGroup_21_3(), "rule__Reference__Group_21_3__0");
					put(grammarAccess.getReferenceAccess().getGroup_22(), "rule__Reference__Group_22__0");
					put(grammarAccess.getOperationAccess().getGroup(), "rule__Operation__Group__0");
					put(grammarAccess.getOperationAccess().getGroup_18(), "rule__Operation__Group_18__0");
					put(grammarAccess.getOperationAccess().getGroup_18_3(), "rule__Operation__Group_18_3__0");
					put(grammarAccess.getParameterAccess().getGroup(), "rule__Parameter__Group__0");
					put(grammarAccess.getMetamodelAccess().getLocationAssignment_3(), "rule__Metamodel__LocationAssignment_3");
					put(grammarAccess.getMetamodelAccess().getContentsAssignment_4_2(), "rule__Metamodel__ContentsAssignment_4_2");
					put(grammarAccess.getMetamodelAccess().getContentsAssignment_4_3_1(), "rule__Metamodel__ContentsAssignment_4_3_1");
					put(grammarAccess.getPackageAccess().getLocationAssignment_3(), "rule__Package__LocationAssignment_3");
					put(grammarAccess.getPackageAccess().getNameAssignment_5(), "rule__Package__NameAssignment_5");
					put(grammarAccess.getPackageAccess().getMetamodelAssignment_7(), "rule__Package__MetamodelAssignment_7");
					put(grammarAccess.getPackageAccess().getContentsAssignment_8_2(), "rule__Package__ContentsAssignment_8_2");
					put(grammarAccess.getPackageAccess().getContentsAssignment_8_3_1(), "rule__Package__ContentsAssignment_8_3_1");
					put(grammarAccess.getClassifier_ImplAccess().getLocationAssignment_3(), "rule__Classifier_Impl__LocationAssignment_3");
					put(grammarAccess.getClassifier_ImplAccess().getNameAssignment_5(), "rule__Classifier_Impl__NameAssignment_5");
					put(grammarAccess.getDataTypeAccess().getLocationAssignment_3(), "rule__DataType__LocationAssignment_3");
					put(grammarAccess.getDataTypeAccess().getNameAssignment_5(), "rule__DataType__NameAssignment_5");
					put(grammarAccess.getEnumerationAccess().getLocationAssignment_3(), "rule__Enumeration__LocationAssignment_3");
					put(grammarAccess.getEnumerationAccess().getNameAssignment_5(), "rule__Enumeration__NameAssignment_5");
					put(grammarAccess.getEnumerationAccess().getLiteralsAssignment_6_2(), "rule__Enumeration__LiteralsAssignment_6_2");
					put(grammarAccess.getEnumerationAccess().getLiteralsAssignment_6_3_1(), "rule__Enumeration__LiteralsAssignment_6_3_1");
					put(grammarAccess.getEnumLiteralAccess().getLocationAssignment_3(), "rule__EnumLiteral__LocationAssignment_3");
					put(grammarAccess.getEnumLiteralAccess().getNameAssignment_5(), "rule__EnumLiteral__NameAssignment_5");
					put(grammarAccess.getEnumLiteralAccess().getEnumAssignment_7(), "rule__EnumLiteral__EnumAssignment_7");
					put(grammarAccess.getTemplateParameterAccess().getLocationAssignment_3(), "rule__TemplateParameter__LocationAssignment_3");
					put(grammarAccess.getTemplateParameterAccess().getNameAssignment_5(), "rule__TemplateParameter__NameAssignment_5");
					put(grammarAccess.getClassAccess().getLocationAssignment_3(), "rule__Class__LocationAssignment_3");
					put(grammarAccess.getClassAccess().getNameAssignment_5(), "rule__Class__NameAssignment_5");
					put(grammarAccess.getClassAccess().getIsAbstractAssignment_7(), "rule__Class__IsAbstractAssignment_7");
					put(grammarAccess.getClassAccess().getParametersAssignment_8_2(), "rule__Class__ParametersAssignment_8_2");
					put(grammarAccess.getClassAccess().getParametersAssignment_8_3_1(), "rule__Class__ParametersAssignment_8_3_1");
					put(grammarAccess.getClassAccess().getSupertypesAssignment_9_2(), "rule__Class__SupertypesAssignment_9_2");
					put(grammarAccess.getClassAccess().getSupertypesAssignment_9_3_1(), "rule__Class__SupertypesAssignment_9_3_1");
					put(grammarAccess.getClassAccess().getStructuralFeaturesAssignment_10_2(), "rule__Class__StructuralFeaturesAssignment_10_2");
					put(grammarAccess.getClassAccess().getStructuralFeaturesAssignment_10_3_1(), "rule__Class__StructuralFeaturesAssignment_10_3_1");
					put(grammarAccess.getClassAccess().getOperationsAssignment_11_2(), "rule__Class__OperationsAssignment_11_2");
					put(grammarAccess.getClassAccess().getOperationsAssignment_11_3_1(), "rule__Class__OperationsAssignment_11_3_1");
					put(grammarAccess.getTypedElement_ImplAccess().getLocationAssignment_3(), "rule__TypedElement_Impl__LocationAssignment_3");
					put(grammarAccess.getTypedElement_ImplAccess().getNameAssignment_5(), "rule__TypedElement_Impl__NameAssignment_5");
					put(grammarAccess.getTypedElement_ImplAccess().getLowerAssignment_7(), "rule__TypedElement_Impl__LowerAssignment_7");
					put(grammarAccess.getTypedElement_ImplAccess().getUpperAssignment_9(), "rule__TypedElement_Impl__UpperAssignment_9");
					put(grammarAccess.getTypedElement_ImplAccess().getIsOrderedAssignment_11(), "rule__TypedElement_Impl__IsOrderedAssignment_11");
					put(grammarAccess.getTypedElement_ImplAccess().getIsUniqueAssignment_13(), "rule__TypedElement_Impl__IsUniqueAssignment_13");
					put(grammarAccess.getTypedElement_ImplAccess().getTypeAssignment_15(), "rule__TypedElement_Impl__TypeAssignment_15");
					put(grammarAccess.getStructuralFeature_ImplAccess().getLocationAssignment_3(), "rule__StructuralFeature_Impl__LocationAssignment_3");
					put(grammarAccess.getStructuralFeature_ImplAccess().getNameAssignment_5(), "rule__StructuralFeature_Impl__NameAssignment_5");
					put(grammarAccess.getStructuralFeature_ImplAccess().getLowerAssignment_7(), "rule__StructuralFeature_Impl__LowerAssignment_7");
					put(grammarAccess.getStructuralFeature_ImplAccess().getUpperAssignment_9(), "rule__StructuralFeature_Impl__UpperAssignment_9");
					put(grammarAccess.getStructuralFeature_ImplAccess().getIsOrderedAssignment_11(), "rule__StructuralFeature_Impl__IsOrderedAssignment_11");
					put(grammarAccess.getStructuralFeature_ImplAccess().getIsUniqueAssignment_13(), "rule__StructuralFeature_Impl__IsUniqueAssignment_13");
					put(grammarAccess.getStructuralFeature_ImplAccess().getTypeAssignment_15(), "rule__StructuralFeature_Impl__TypeAssignment_15");
					put(grammarAccess.getStructuralFeature_ImplAccess().getOwnerAssignment_17(), "rule__StructuralFeature_Impl__OwnerAssignment_17");
					put(grammarAccess.getStructuralFeature_ImplAccess().getSubsetOfAssignment_18_2(), "rule__StructuralFeature_Impl__SubsetOfAssignment_18_2");
					put(grammarAccess.getStructuralFeature_ImplAccess().getSubsetOfAssignment_18_3_1(), "rule__StructuralFeature_Impl__SubsetOfAssignment_18_3_1");
					put(grammarAccess.getStructuralFeature_ImplAccess().getDerivedFromAssignment_19_2(), "rule__StructuralFeature_Impl__DerivedFromAssignment_19_2");
					put(grammarAccess.getStructuralFeature_ImplAccess().getDerivedFromAssignment_19_3_1(), "rule__StructuralFeature_Impl__DerivedFromAssignment_19_3_1");
					put(grammarAccess.getAttributeAccess().getLocationAssignment_3(), "rule__Attribute__LocationAssignment_3");
					put(grammarAccess.getAttributeAccess().getNameAssignment_5(), "rule__Attribute__NameAssignment_5");
					put(grammarAccess.getAttributeAccess().getLowerAssignment_7(), "rule__Attribute__LowerAssignment_7");
					put(grammarAccess.getAttributeAccess().getUpperAssignment_9(), "rule__Attribute__UpperAssignment_9");
					put(grammarAccess.getAttributeAccess().getIsOrderedAssignment_11(), "rule__Attribute__IsOrderedAssignment_11");
					put(grammarAccess.getAttributeAccess().getIsUniqueAssignment_13(), "rule__Attribute__IsUniqueAssignment_13");
					put(grammarAccess.getAttributeAccess().getTypeAssignment_15(), "rule__Attribute__TypeAssignment_15");
					put(grammarAccess.getAttributeAccess().getOwnerAssignment_17(), "rule__Attribute__OwnerAssignment_17");
					put(grammarAccess.getAttributeAccess().getSubsetOfAssignment_18_2(), "rule__Attribute__SubsetOfAssignment_18_2");
					put(grammarAccess.getAttributeAccess().getSubsetOfAssignment_18_3_1(), "rule__Attribute__SubsetOfAssignment_18_3_1");
					put(grammarAccess.getAttributeAccess().getDerivedFromAssignment_19_2(), "rule__Attribute__DerivedFromAssignment_19_2");
					put(grammarAccess.getAttributeAccess().getDerivedFromAssignment_19_3_1(), "rule__Attribute__DerivedFromAssignment_19_3_1");
					put(grammarAccess.getReferenceAccess().getLocationAssignment_3(), "rule__Reference__LocationAssignment_3");
					put(grammarAccess.getReferenceAccess().getNameAssignment_5(), "rule__Reference__NameAssignment_5");
					put(grammarAccess.getReferenceAccess().getLowerAssignment_7(), "rule__Reference__LowerAssignment_7");
					put(grammarAccess.getReferenceAccess().getUpperAssignment_9(), "rule__Reference__UpperAssignment_9");
					put(grammarAccess.getReferenceAccess().getIsOrderedAssignment_11(), "rule__Reference__IsOrderedAssignment_11");
					put(grammarAccess.getReferenceAccess().getIsUniqueAssignment_13(), "rule__Reference__IsUniqueAssignment_13");
					put(grammarAccess.getReferenceAccess().getIsContainerAssignment_15(), "rule__Reference__IsContainerAssignment_15");
					put(grammarAccess.getReferenceAccess().getTypeAssignment_17(), "rule__Reference__TypeAssignment_17");
					put(grammarAccess.getReferenceAccess().getOwnerAssignment_19(), "rule__Reference__OwnerAssignment_19");
					put(grammarAccess.getReferenceAccess().getSubsetOfAssignment_20_2(), "rule__Reference__SubsetOfAssignment_20_2");
					put(grammarAccess.getReferenceAccess().getSubsetOfAssignment_20_3_1(), "rule__Reference__SubsetOfAssignment_20_3_1");
					put(grammarAccess.getReferenceAccess().getDerivedFromAssignment_21_2(), "rule__Reference__DerivedFromAssignment_21_2");
					put(grammarAccess.getReferenceAccess().getDerivedFromAssignment_21_3_1(), "rule__Reference__DerivedFromAssignment_21_3_1");
					put(grammarAccess.getReferenceAccess().getOppositeAssignment_22_1(), "rule__Reference__OppositeAssignment_22_1");
					put(grammarAccess.getOperationAccess().getLocationAssignment_3(), "rule__Operation__LocationAssignment_3");
					put(grammarAccess.getOperationAccess().getNameAssignment_5(), "rule__Operation__NameAssignment_5");
					put(grammarAccess.getOperationAccess().getLowerAssignment_7(), "rule__Operation__LowerAssignment_7");
					put(grammarAccess.getOperationAccess().getUpperAssignment_9(), "rule__Operation__UpperAssignment_9");
					put(grammarAccess.getOperationAccess().getIsOrderedAssignment_11(), "rule__Operation__IsOrderedAssignment_11");
					put(grammarAccess.getOperationAccess().getIsUniqueAssignment_13(), "rule__Operation__IsUniqueAssignment_13");
					put(grammarAccess.getOperationAccess().getTypeAssignment_15(), "rule__Operation__TypeAssignment_15");
					put(grammarAccess.getOperationAccess().getOwnerAssignment_17(), "rule__Operation__OwnerAssignment_17");
					put(grammarAccess.getOperationAccess().getParametersAssignment_18_2(), "rule__Operation__ParametersAssignment_18_2");
					put(grammarAccess.getOperationAccess().getParametersAssignment_18_3_1(), "rule__Operation__ParametersAssignment_18_3_1");
					put(grammarAccess.getParameterAccess().getLocationAssignment_3(), "rule__Parameter__LocationAssignment_3");
					put(grammarAccess.getParameterAccess().getNameAssignment_5(), "rule__Parameter__NameAssignment_5");
					put(grammarAccess.getParameterAccess().getLowerAssignment_7(), "rule__Parameter__LowerAssignment_7");
					put(grammarAccess.getParameterAccess().getUpperAssignment_9(), "rule__Parameter__UpperAssignment_9");
					put(grammarAccess.getParameterAccess().getIsOrderedAssignment_11(), "rule__Parameter__IsOrderedAssignment_11");
					put(grammarAccess.getParameterAccess().getIsUniqueAssignment_13(), "rule__Parameter__IsUniqueAssignment_13");
					put(grammarAccess.getParameterAccess().getTypeAssignment_15(), "rule__Parameter__TypeAssignment_15");
					put(grammarAccess.getParameterAccess().getOwnerAssignment_17(), "rule__Parameter__OwnerAssignment_17");
				}
			};
		}
		return nameMappings.get(element);
	}

	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			InternalKM3Parser typedParser = (InternalKM3Parser) parser;
			typedParser.entryRuleMetamodel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public KM3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KM3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
