/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext.ui;

import com.google.inject.Injector;
import org.eclipse.m2m.km3.xtext.ui.internal.XtextActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class KM3ExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return XtextActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return XtextActivator.getInstance().getInjector(XtextActivator.ORG_ECLIPSE_M2M_KM3_XTEXT_KM3);
	}
	
}
