/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext.ui;

import org.eclipse.m2m.km3.xtext.ui.AbstractKM3UiModule;
import org.eclipse.ui.plugin.AbstractUIPlugin;
import org.eclipse.xtend.lib.annotations.FinalFieldsConstructor;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
@FinalFieldsConstructor
@SuppressWarnings("all")
public class KM3UiModule extends AbstractKM3UiModule {
  public KM3UiModule(final AbstractUIPlugin plugin) {
    super(plugin);
  }
}
