/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class KM3AntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("org/eclipse/m2m/km3/xtext/parser/antlr/internal/InternalKM3.tokens");
	}
}
