/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext.parser.antlr;

import com.google.inject.Inject;
import org.eclipse.m2m.km3.xtext.parser.antlr.internal.InternalKM3Parser;
import org.eclipse.m2m.km3.xtext.services.KM3GrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class KM3Parser extends AbstractAntlrParser {

	@Inject
	private KM3GrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalKM3Parser createParser(XtextTokenStream stream) {
		return new InternalKM3Parser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "Package";
	}

	public KM3GrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(KM3GrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
