/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext.serializer;

import com.google.inject.Inject;
import java.util.Set;
import km3.Attribute;
import km3.DataType;
import km3.Km3Package;
import km3.Metamodel;
import km3.Reference;
import org.eclipse.emf.ecore.EObject;
import org.eclipse.emf.ecore.EPackage;
import org.eclipse.m2m.km3.xtext.services.KM3GrammarAccess;
import org.eclipse.xtext.Action;
import org.eclipse.xtext.Parameter;
import org.eclipse.xtext.ParserRule;
import org.eclipse.xtext.serializer.ISerializationContext;
import org.eclipse.xtext.serializer.acceptor.SequenceFeeder;
import org.eclipse.xtext.serializer.sequencer.AbstractDelegatingSemanticSequencer;
import org.eclipse.xtext.serializer.sequencer.ITransientValueService.ValueTransient;

@SuppressWarnings("all")
public class KM3SemanticSequencer extends AbstractDelegatingSemanticSequencer {

	@Inject
	private KM3GrammarAccess grammarAccess;
	
	@Override
	public void sequence(ISerializationContext context, EObject semanticObject) {
		EPackage epackage = semanticObject.eClass().getEPackage();
		ParserRule rule = context.getParserRule();
		Action action = context.getAssignedAction();
		Set<Parameter> parameters = context.getEnabledBooleanParameters();
		if (epackage == Km3Package.eINSTANCE)
			switch (semanticObject.eClass().getClassifierID()) {
			case Km3Package.ATTRIBUTE:
				sequence_Attribute(context, (Attribute) semanticObject); 
				return; 
			case Km3Package.CLASS:
				sequence_Class(context, (km3.Class) semanticObject); 
				return; 
			case Km3Package.DATA_TYPE:
				sequence_DataType(context, (DataType) semanticObject); 
				return; 
			case Km3Package.METAMODEL:
				sequence_Metamodel(context, (Metamodel) semanticObject); 
				return; 
			case Km3Package.PACKAGE:
				sequence_Package(context, (km3.Package) semanticObject); 
				return; 
			case Km3Package.REFERENCE:
				sequence_Reference(context, (Reference) semanticObject); 
				return; 
			}
		if (errorAcceptor != null)
			errorAcceptor.accept(diagnosticProvider.createInvalidContextOrTypeDiagnostic(semanticObject, context));
	}
	
	/**
	 * Contexts:
	 *     StructuralFeature returns Attribute
	 *     Attribute returns Attribute
	 *
	 * Constraint:
	 *     (isUnique?='unique'? name=ID isOrdered?='ordered'? type=[Classifier|ID])
	 */
	protected void sequence_Attribute(ISerializationContext context, Attribute semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ModelElement returns Class
	 *     Class returns Class
	 *
	 * Constraint:
	 *     (isAbstract?='abstract'? name=ID (supertypes+=[Class|ID] supertypes+=[Class|ID]*)? structuralFeatures+=StructuralFeature*)
	 */
	protected void sequence_Class(ISerializationContext context, km3.Class semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     ModelElement returns DataType
	 *     DataType returns DataType
	 *
	 * Constraint:
	 *     name=ID
	 */
	protected void sequence_DataType(ISerializationContext context, DataType semanticObject) {
		if (errorAcceptor != null) {
			if (transientValues.isValueTransient(semanticObject, Km3Package.Literals.MODEL_ELEMENT__NAME) == ValueTransient.YES)
				errorAcceptor.accept(diagnosticProvider.createFeatureValueMissing(semanticObject, Km3Package.Literals.MODEL_ELEMENT__NAME));
		}
		SequenceFeeder feeder = createSequencerFeeder(context, semanticObject);
		feeder.accept(grammarAccess.getDataTypeAccess().getNameIDTerminalRuleCall_1_0(), semanticObject.getName());
		feeder.finish();
	}
	
	
	/**
	 * Contexts:
	 *     Metamodel returns Metamodel
	 *
	 * Constraint:
	 *     contents+=Package*
	 */
	protected void sequence_Metamodel(ISerializationContext context, Metamodel semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     Package returns Package
	 *
	 * Constraint:
	 *     (name=ID contents+=ModelElement*)
	 */
	protected void sequence_Package(ISerializationContext context, km3.Package semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
	/**
	 * Contexts:
	 *     StructuralFeature returns Reference
	 *     Reference returns Reference
	 *
	 * Constraint:
	 *     (name=ID isOrdered?='ordered'? isContainer?='container'? type=[Classifier|ID] opposite=[Reference|ID]?)
	 */
	protected void sequence_Reference(ISerializationContext context, Reference semanticObject) {
		genericSequencer.createSequence(context, semanticObject);
	}
	
	
}
