/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext;

import org.eclipse.m2m.km3.xtext.AbstractKM3RuntimeModule;
import org.eclipse.m2m.km3.xtext.converter.MultiplicityValueConverterService;
import org.eclipse.xtext.conversion.IValueConverterService;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
@SuppressWarnings("all")
public class KM3RuntimeModule extends AbstractKM3RuntimeModule {
  @Override
  public Class<? extends IValueConverterService> bindIValueConverterService() {
    return MultiplicityValueConverterService.class;
  }
}
