/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext;

/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
@SuppressWarnings("all")
public class KM3StandaloneSetup /* implements KM3StandaloneSetupGenerated  */{
  public static void doSetup() {
    throw new Error("Unresolved compilation problems:"
      + "\nThe method createInjectorAndDoEMFRegistration() is undefined for the type KM3StandaloneSetup");
  }
}
