/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext.ui.quickfix;

import org.eclipse.xtext.ui.editor.quickfix.DefaultQuickfixProvider;

/**
 * Custom quickfixes.
 * 
 * See https://www.eclipse.org/Xtext/documentation/310_eclipse_support.html#quick-fixes
 */
@SuppressWarnings("all")
public class KM3QuickfixProvider extends DefaultQuickfixProvider {
}
