/**
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext.validation;

/**
 * This class contains custom validation rules.
 * 
 * See https://www.eclipse.org/Xtext/documentation/303_runtime_concepts.html#validation
 */
@SuppressWarnings("all")
public class KM3Validator /* implements AbstractKM3Validator  */{
}
