/*
 * generated by Xtext 2.10.0
 */
package org.eclipse.m2m.km3.xtext.tests

import com.google.inject.Inject
import org.eclipse.m2m.km3.Metamodel
import org.eclipse.xtext.junit4.InjectWith
import org.eclipse.xtext.junit4.XtextRunner
import org.eclipse.xtext.junit4.util.ParseHelper
import org.junit.Assert
import org.junit.Test
import org.junit.runner.RunWith

@RunWith(XtextRunner)
@InjectWith(KM3InjectorProvider)
class KM3ParsingTest{

	@Inject
	ParseHelper<Metamodel> parseHelper

	@Test 
	def void loadModel() {
		val result = parseHelper.parse('''
			Hello Xtext!
		''')
		Assert.assertNotNull(result)
	}
}
